# MkDocs configuration for STIsim
# https://www.mkdocs.org/user-guide/configuration/

site_name: STIsim
site_description: Agent-based modeling framework for sexually-transmitted infections
site_url: https://docs.idmod.org/projects/stisim

repo_name: starsimhub/stisim
repo_url: https://github.com/starsimhub/stisim
edit_uri: edit/main/docs/

copyright: "1999 &ndash; 2025 Gates Foundation. All rights reserved."

theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  logo: images/idm-logo-transparent.png
  favicon: images/favicon.ico
  features:
    - navigation.footer # include a footer with links to privacy, terms, etc.
    - content.code.copy # enable copy buttons for code blocks
    - navigation.indexes # enable parent index page for sections
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: white
      accent: light blue
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: light blue

nav:
  - Home: index.md
  - Overview: overview.md
  - Tutorials: tutorials.md
  - What's new: whatsnew.md
  - API reference: api.md

# icons, semantic markup, emojis
markdown_extensions:
  - toc:
      toc_depth: 3
  - attr_list # enables HTMl and CSS classes to inline elements
  - md_in_html # enables grids
  - admonition # warnings, etc.
  - def_list
  - footnotes

# javascript customization for math
extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - customization/css/extra.css # custom CSS for footer spacing
plugins:
  - search # search functionality
  - autorefs # automatically create linkable references
  - include-markdown # include other files, such as READMEs
  - mkdocs-jupyter: # enables Jupyter notebooks to be rendered
      execute: false
      allow_errors: true
      include_source: true
  - mkdocstrings: # process docstrings to generate API reference
      handlers:
        python:
          paths: [src] # path to source code
          options:
            docstring_style: google
            show_source: false
            merge_init_into_class: true
            heading_level: 2
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_toc_entry: true
            show_object_full_path: true

copyright: Copyright &copy; 2025 Gates Foundation. All rights reserved.

extra:
  generator: false
  footer_links:
    - text: "Privacy and Cookies Notice"
      href: "https://www.gatesfoundation.org/Privacy-and-Cookies-Notice"
    - text: "Terms of Use"
      href: "https://www.gatesfoundation.org/Terms-of-Use"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/InstituteforDiseaseModeling/laser-generic # update to your repo
    - icon: fontawesome/regular/envelope
      link: mailto:idm@gatesfoundation.org
    - icon: octicons/globe-24
      link: https://idmod.org
    - icon: simple/youtube
      link: http://www.youtube.com/@institutefordiseasemodelin1987
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/institute-disease-modeling

  analytics:
    property: GTM-NK4K647
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback! If you like, provide additional information by
            using our <a href="https://app.smartsheet.com/b/form/ec8dbb77809949ecab7286a5ca74a206" target="_blank" rel="noopener">feedback form</a>.
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://app.smartsheet.com/b/form/ec8dbb77809949ecab7286a5ca74a206" target="_blank" rel="noopener">feedback form</a>.
