# MkDocs configuration for STIsim
# https://www.mkdocs.org/user-guide/configuration/

site_name: STIsim
site_description: Agent-based modeling framework for sexually-transmitted infections
site_url: https://docs.idmod.org/projects/stisim

repo_name: starsimhub/stisim
repo_url: https://github.com/starsimhub/stisim
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2024-2026 Gates Foundation. All rights reserved.

theme:
  name: material
  font:
    text: Raleway
    code: Roboto Mono
  logo: assets/starsim-logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.footer # include a footer with links to privacy, terms, etc.
    - content.code.copy # enable copy buttons for code blocks
    - navigation.indexes # enable parent index page for sections
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: white
      accent: cyan
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: cyan

nav:
  - Home: index.md
  - Overview: overview.md
  - Tutorials:
    - tutorials.md
    - Getting started: tutorials/tut_intro.ipynb
    - Co-transmitting STIs: tutorials/tut_cotransmission.ipynb
    - Results and plotting: tutorials/tut_results.ipynb
  - User guide:
    - user_guide/userguide.md
    - Diseases:
      - user_guide/diseases/index.md
      - HIV: user_guide/diseases/hiv.md
      - Syphilis: user_guide/diseases/syphilis.md
      - Chlamydia: user_guide/diseases/chlamydia.md
      - Gonorrhea: user_guide/diseases/gonorrhea.md
      - Trichomoniasis: user_guide/diseases/trichomoniasis.md
      - Bacterial vaginosis: user_guide/diseases/bv.md
      - Genital ulcer disease: user_guide/diseases/gud.md
    - Networks:
      - Structured sexual: user_guide/networks/structured_sexual.md
  - What's new: whatsnew.md
  - Code of conduct: code_of_conduct.md
  - Contributing: contributing.md
  - API reference: api.md

# icons, semantic markup, emojis
markdown_extensions:
  - toc:
      toc_depth: 3
  - attr_list # enables HTMl and CSS classes to inline elements
  - md_in_html # enables grids
  - admonition # warnings, etc.
  - def_list
  - footnotes

# javascript customization for math
extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - customization/css/extra.css # custom CSS for footer spacing
plugins:
  - search # search functionality
  - autorefs # automatically create linkable references
  - include-markdown # include other files, such as READMEs
  - mkdocs-jupyter: # enables Jupyter notebooks to be rendered
      execute: true
      allow_errors: true
      include_source: true
      kernel_name: python3
  - mkdocstrings: # process docstrings to generate API reference
      handlers:
        python:
          paths: [.] # path to source code
          options:
            docstring_style: google
            show_source: false
            merge_init_into_class: true
            heading_level: 2
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_toc_entry: true
            show_object_full_path: true

extra:
  generator: false
  footer_links:
    - text: "Privacy and Cookies Notice"
      href: "https://www.gatesfoundation.org/Privacy-and-Cookies-Notice"
    - text: "Terms of Use"
      href: "https://www.gatesfoundation.org/Terms-of-Use"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/starsimhub/stisim
    - icon: fontawesome/regular/envelope
      link: mailto:info@starsim.org
    - icon: fontawesome/brands/slack
      link: https://starsim-idm.slack.com
    - icon: octicons/globe-24
      link: https://starsim.org

  analytics:
    property: GTM-NK4K647
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback! If you like, provide additional information by
            using our <a href="https://app.smartsheet.com/b/form/ec8dbb77809949ecab7286a5ca74a206" target="_blank" rel="noopener">feedback form</a>.
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://app.smartsheet.com/b/form/ec8dbb77809949ecab7286a5ca74a206" target="_blank" rel="noopener">feedback form</a>.
